// src/lib/items.ts
// Dados brutos de itens para importação inicial do estoque.
// Cada item sempre tem todas as chaves abaixo; quando a planilha de origem não tinha um
// valor para o campo, ele fica como string vazia (tratado na tela de importação/front).
export interface ItemImportado {
  nome: string;
  // Nome do projeto (não é o id numérico ainda — db.ts resolve o id ao popular o banco).
  // Vazio quando o item não tem projeto associado.
  projeto_id: string;
  quantidade: number;
  prateleira: string;
  piso_andar: string;
  local_setor: string;
  organizador: string;
}

export const items: ItemImportado[] = [
  {
    nome: "Maçarico",
    projeto_id: "",
    quantidade: 1,
    prateleira: "",
    piso_andar: "",
    local_setor: "",
    organizador: "50",
  },
  {
    nome: "Eletrodo E6013",
    projeto_id: "",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P4",
    local_setor: "B",
    organizador: "48",
  },
  {
    nome: "Chave de boca",
    projeto_id: "Uso geral",
    quantidade: 10,
    prateleira: "10",
    piso_andar: "P5",
    local_setor: "A",
    organizador: "49",
  },
  {
    nome: "Disco de desbaste 230mm",
    projeto_id: "Uso geral",
    quantidade: 3,
    prateleira: "10",
    piso_andar: "P3",
    local_setor: "A",
    organizador: "45",
  },
  {
    nome: "Pistola de pintura elétrica",
    projeto_id: "Uso geral",
    quantidade: 1,
    prateleira: "8",
    piso_andar: "P3",
    local_setor: "A",
    organizador: "X",
  },
  {
    nome: "Lamina de serra manual STARRETT",
    projeto_id: "Uso geral",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P2",
    local_setor: "r",
    organizador: "43",
  },
  {
    nome: "Disjuntor bipolar ELETROMEC",
    projeto_id: "Uso geral",
    quantidade: 3,
    prateleira: "9",
    piso_andar: "P2",
    local_setor: "B",
    organizador: "54",
  },
  {
    nome: "Lixa",
    projeto_id: "Uso geral",
    quantidade: 2,
    prateleira: "10",
    piso_andar: "P4",
    local_setor: "A",
    organizador: "47",
  },
  {
    nome: "Serra fita",
    projeto_id: "Uso geral",
    quantidade: 1,
    prateleira: "8",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "61",
  },
  {
    nome: "Disco Flap",
    projeto_id: "Uso geral",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P3",
    local_setor: "A",
    organizador: "45",
  },
  {
    nome: "Disjuntor bipolar GE",
    projeto_id: "Uso geral",
    quantidade: 3,
    prateleira: "9",
    piso_andar: "P2",
    local_setor: "B",
    organizador: "54",
  },
  {
    nome: "Lixa",
    projeto_id: "Uso geral",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P4",
    local_setor: "A",
    organizador: "47",
  },
  {
    nome: "Kit de agulhas hipodérmicas",
    projeto_id: "Soar",
    quantidade: 1,
    prateleira: "3",
    piso_andar: "P2",
    local_setor: "A",
    organizador: "20",
  },
  {
    nome: "Fita teflon KAPTON",
    projeto_id: "revite",
    quantidade: 1,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Fita teflon",
    projeto_id: "revite",
    quantidade: 1,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Fita crepe amarlea",
    projeto_id: "",
    quantidade: 1,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Fita crepe verde",
    projeto_id: "",
    quantidade: 1,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Misturador de gases Witt",
    projeto_id: "",
    quantidade: 1,
    prateleira: "",
    piso_andar: "",
    local_setor: "",
    organizador: "X",
  },
  {
    nome: "Parafuso Allen M6x50",
    projeto_id: "",
    quantidade: 8,
    prateleira: "Prateleira de parafusos",
    piso_andar: "",
    local_setor: "",
    organizador: "",
  },
  {
    nome: "Parafuso Allen M6x65",
    projeto_id: "",
    quantidade: 2,
    prateleira: "Prateleira de parafusos",
    piso_andar: "",
    local_setor: "",
    organizador: "",
  },
  {
    nome: "Parafuso Allen M6x100",
    projeto_id: "",
    quantidade: 6,
    prateleira: "Prateleira de parafusos",
    piso_andar: "",
    local_setor: "",
    organizador: "",
  },
  {
    nome: "Parafuso Allen M5x35",
    projeto_id: "",
    quantidade: 4,
    prateleira: "Prateleira de parafusos",
    piso_andar: "",
    local_setor: "",
    organizador: "",
  },
  {
    nome: "Arruela lisa M5",
    projeto_id: "",
    quantidade: 4,
    prateleira: "Prateleira de parafusos",
    piso_andar: "",
    local_setor: "",
    organizador: "",
  },
  {
    nome: "Porca M6",
    projeto_id: "",
    quantidade: 14,
    prateleira: "Prateleira de parafusos",
    piso_andar: "",
    local_setor: "",
    organizador: "",
  },
  {
    nome: "WebCam C3tech WB-100",
    projeto_id: "",
    quantidade: 1,
    prateleira: "Equipamento em cima do palet",
    piso_andar: "",
    local_setor: "",
    organizador: "",
  },
  {
    nome: "Câmera XIR-1800",
    projeto_id: "",
    quantidade: 1,
    prateleira: "Equipamento em cima do palet",
    piso_andar: "",
    local_setor: "",
    organizador: "",
  },
  {
    nome: "Fita teflon",
    projeto_id: "revite",
    quantidade: 1,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Fita teflon KAPTON",
    projeto_id: "revite",
    quantidade: 1,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Parafuso M8X1,25",
    projeto_id: "",
    quantidade: 4,
    prateleira: "Prateleira de parafusos",
    piso_andar: "",
    local_setor: "",
    organizador: "",
  },
  {
    nome: "Abraçadeira de tubo hidráulico",
    projeto_id: "Uso geral",
    quantidade: 2,
    prateleira: "8",
    piso_andar: "P1",
    local_setor: "B",
    organizador: "62",
  },
  {
    nome: "Veda fresta",
    projeto_id: "VBA",
    quantidade: 1,
    prateleira: "4",
    piso_andar: "P2",
    local_setor: "A",
    organizador: "29",
  },
  {
    nome: "Monitor 23.8'' AOC",
    projeto_id: "CEMIG",
    quantidade: 5,
    prateleira: "X",
    piso_andar: "X",
    local_setor: "X",
    organizador: "X",
  },
  {
    nome: "Súbito 18-35mm AMATOOLS",
    projeto_id: "Uso geral",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "41",
  },
  {
    nome: "Súbito 10-18mm Dasqua",
    projeto_id: "Uso geral",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "41",
  },
  {
    nome: "Micrômetro 0-25mm INSIZE",
    projeto_id: "Uso geral",
    quantidade: 2,
    prateleira: "10",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "41",
  },
  {
    nome: "Micrômetro 25-50mm INSIZE",
    projeto_id: "Uso geral",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "41",
  },
  {
    nome: "Micrômetro 50-75mm INSIZE",
    projeto_id: "Uso geral",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "41",
  },
  {
    nome: "Relogio apalpador INSIZE",
    projeto_id: "Uso geral",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "41",
  },
  {
    nome: "Micrômetro interno 20-25mm Mitutoyo",
    projeto_id: "Uso geral",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "41",
  },
  {
    nome: "Pincel 3\" VONDER",
    projeto_id: "Uso geral",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P2",
    local_setor: "A",
    organizador: "43",
  },
  {
    nome: "Arco de serra TRAMONTINA",
    projeto_id: "Uso geral",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P2",
    local_setor: "A",
    organizador: "43",
  },
  {
    nome: "Lamina de serra manual STARRETT",
    projeto_id: "Uso geral",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P2",
    local_setor: "A",
    organizador: "43",
  },
  {
    nome: "Tampão 1/4\" BSP",
    projeto_id: "Soar",
    quantidade: 1,
    prateleira: "3",
    piso_andar: "P1",
    local_setor: "B",
    organizador: "19",
  },
  {
    nome: "Conector 1/4\" BSP engate rápido",
    projeto_id: "Soar",
    quantidade: 1,
    prateleira: "3",
    piso_andar: "P1",
    local_setor: "B",
    organizador: "19",
  },
  {
    nome: "Fluido de freio DOT 4",
    projeto_id: "VBA",
    quantidade: 5,
    prateleira: "4",
    piso_andar: "P4",
    local_setor: "B",
    organizador: "34",
  },
  {
    nome: "Disco de corte 115x1x22,23",
    projeto_id: "Uso geral",
    quantidade: 3,
    prateleira: "10",
    piso_andar: "P2",
    local_setor: "B",
    organizador: "44",
  },
  {
    nome: "Jogo de chave Allen VONDER 1.5 - 10mm",
    projeto_id: "Uso geral",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P2",
    local_setor: "A",
    organizador: "43",
  },
  {
    nome: "Sensor de proximidade indutivo M12",
    projeto_id: "Itens consumiveis",
    quantidade: 1,
    prateleira: "9",
    piso_andar: "P2",
    local_setor: "A",
    organizador: "53",
  },
  {
    nome: "Monitor",
    projeto_id: "Uso geral",
    quantidade: 6,
    prateleira: "7",
    piso_andar: "X",
    local_setor: "X",
    organizador: "X",
  },
  {
    nome: "Disco de corte 115x1x22,23",
    projeto_id: "Itens consumiveis",
    quantidade: 5,
    prateleira: "10",
    piso_andar: "P2",
    local_setor: "B",
    organizador: "44",
  },
  {
    nome: "Disco de corte 180x3x22,3",
    projeto_id: "Itens consumiveis",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "46",
  },
  {
    nome: "Disco de corte 180x3x22,3",
    projeto_id: "Itens consumiveis",
    quantidade: 5,
    prateleira: "10",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "46",
  },
  {
    nome: "Disco de corte 115x1x22,23",
    projeto_id: "Itens consumiveis",
    quantidade: 5,
    prateleira: "10",
    piso_andar: "P2",
    local_setor: "B",
    organizador: "44",
  },
  {
    nome: "Chave torx T30",
    projeto_id: "Ferramentas",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P5",
    local_setor: "A",
    organizador: "49",
  },
  {
    nome: "Chave torx T20",
    projeto_id: "Ferramentas",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P5",
    local_setor: "A",
    organizador: "49",
  },
  {
    nome: "Termômetro",
    projeto_id: "revite",
    quantidade: 2,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Módulo de controle SIEMENS",
    projeto_id: "revite",
    quantidade: 1,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Regulador de pressão",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "1",
  },
  {
    nome: "Mascara de solda ESAB",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P1",
    local_setor: "B",
    organizador: "2",
  },
  {
    nome: "Tocha de soldagem FRONIUS",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "4",
  },
  {
    nome: "Guia para corte em maçarico",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P2",
    local_setor: "A",
    organizador: "X",
  },
  {
    nome: "IHM SIEMENS",
    projeto_id: "Soar",
    quantidade: 1,
    prateleira: "3",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "18",
  },
  {
    nome: "Servo motor",
    projeto_id: "Soar",
    quantidade: 1,
    prateleira: "3",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "23",
  },
  {
    nome: "Cabo de sinal c/ conectores SIEMENS",
    projeto_id: "Soar",
    quantidade: 2,
    prateleira: "3",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "23",
  },
  {
    nome: "Cabo de POT c/ conectores SIEMENS",
    projeto_id: "Soar",
    quantidade: 2,
    prateleira: "3",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "23",
  },
  {
    nome: "Disco de corte 115x1x22,23mm",
    projeto_id: "Itens consumiveis",
    quantidade: 3,
    prateleira: "10",
    piso_andar: "P2",
    local_setor: "B",
    organizador: "44",
  },
  {
    nome: "Disco de desbaste 115x22,23mm",
    projeto_id: "Itens consumiveis",
    quantidade: 5,
    prateleira: "10",
    piso_andar: "P3",
    local_setor: "A",
    organizador: "45",
  },
  {
    nome: "Fio de termopar macho",
    projeto_id: "revite",
    quantidade: 19,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Botão de emergência",
    projeto_id: "revite",
    quantidade: 2,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Borne para USB",
    projeto_id: "revite",
    quantidade: 0,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Borne para cabo de rede",
    projeto_id: "revite",
    quantidade: 0,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Chave liga/desliga",
    projeto_id: "revite",
    quantidade: 0,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "IHM DELTA",
    projeto_id: "revite",
    quantidade: 0,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Botão de emergência",
    projeto_id: "revite",
    quantidade: 0,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Terminal encaixe fêmea",
    projeto_id: "revite",
    quantidade: 0,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Módulo de controle SIEMENS",
    projeto_id: "revite",
    quantidade: 0,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Disco de corte 115x1x22,23mm",
    projeto_id: "Itens consumiveis",
    quantidade: 3,
    prateleira: "10",
    piso_andar: "P2",
    local_setor: "B",
    organizador: "44",
  },
  {
    nome: "Analisador de gás Witt",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "2",
    piso_andar: "P5",
    local_setor: "B",
    organizador: "X",
  },
  {
    nome: "Disco de corte 115x1x22,23mm",
    projeto_id: "Itens consumiveis",
    quantidade: 2,
    prateleira: "10",
    piso_andar: "P2",
    local_setor: "B",
    organizador: "44",
  },
  {
    nome: "Termopar",
    projeto_id: "revite",
    quantidade: 19,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Termopar fêmea",
    projeto_id: "revite",
    quantidade: 13,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Fio de termopar macho",
    projeto_id: "revite",
    quantidade: 19,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "14",
  },
  {
    nome: "Pano de limpeza",
    projeto_id: "Itens consumiveis",
    quantidade: 5,
    prateleira: "Equipamento em cima do palet",
    piso_andar: "",
    local_setor: "",
    organizador: "",
  },
  {
    nome: "Chave fim de curso MICRO SWITCH",
    projeto_id: "Soar",
    quantidade: 2,
    prateleira: "3",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "18",
  },
  {
    nome: "Sensor indutivo M12",
    projeto_id: "Itens consumiveis",
    quantidade: 1,
    prateleira: "9",
    piso_andar: "P2",
    local_setor: "A",
    organizador: "53",
  },
  {
    nome: "Conector de engate rápido 6mm",
    projeto_id: "Soar",
    quantidade: 1,
    prateleira: "3",
    piso_andar: "P1",
    local_setor: "B",
    organizador: "19",
  },
  {
    nome: "Controle remoto Samsung",
    projeto_id: "CEMIG",
    quantidade: 1,
    prateleira: "2",
    piso_andar: "P2",
    local_setor: "A",
    organizador: "11",
  },
  {
    nome: "TV samsung 50\"",
    projeto_id: "CEMIG",
    quantidade: 1,
    prateleira: "Equipamento entre a prateleira 5 e 6",
    piso_andar: "",
    local_setor: "",
    organizador: "",
  },
  {
    nome: "Rodízios",
    projeto_id: "Itens consumiveis",
    quantidade: 4,
    prateleira: "9",
    piso_andar: "P5",
    local_setor: "B",
    organizador: "60",
  },
  {
    nome: "Monitor 23.8'' AOC",
    projeto_id: "CEMIG",
    quantidade: 2,
    prateleira: "6",
    piso_andar: "3",
    local_setor: "A",
    organizador: "X",
  },
  {
    nome: "Kit imãs",
    projeto_id: "Soar",
    quantidade: 1,
    prateleira: "3",
    piso_andar: "P2",
    local_setor: "A",
    organizador: "20",
  },
  {
    nome: "Serra Fita 19x6 2,37m",
    projeto_id: "Itens consumiveis",
    quantidade: 11,
    prateleira: "8",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "61",
  },
  {
    nome: "Monitor 27''",
    projeto_id: "revite",
    quantidade: 1,
    prateleira: "6",
    piso_andar: "P3",
    local_setor: "AB",
    organizador: "X",
  },
  {
    nome: "Revelador SKD S2",
    projeto_id: "Mada",
    quantidade: 2,
    prateleira: "1",
    piso_andar: "P2",
    local_setor: "A",
    organizador: "3",
  },
  {
    nome: "Fita Isolante 19mm x 20m",
    projeto_id: "VBA",
    quantidade: 1,
    prateleira: "4",
    piso_andar: "P2",
    local_setor: "B",
    organizador: "30",
  },
  {
    nome: "Kit câmera Basler Lens C23 5M",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P4",
    local_setor: "A",
    organizador: "5",
  },
  {
    nome: "Cabo Manga",
    projeto_id: "Soar",
    quantidade: 1,
    prateleira: "3",
    piso_andar: "P2",
    local_setor: "B",
    organizador: "21",
  },
  {
    nome: "Guia Linear",
    projeto_id: "Soar",
    quantidade: 1,
    prateleira: "3",
    piso_andar: "P3",
    local_setor: "A",
    organizador: "22",
  },
  {
    nome: "Conjunto tocha TBI",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "73",
  },
  {
    nome: "Anticolisão",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P4",
    local_setor: "A",
    organizador: "5",
  },
  {
    nome: "Analisador de gás portatil",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "2",
    piso_andar: "P5",
    local_setor: "B",
    organizador: "X",
  },
  {
    nome: "Cabos TV Samsung",
    projeto_id: "CEMIG",
    quantidade: 1,
    prateleira: "2",
    piso_andar: "P2",
    local_setor: "A",
    organizador: "11",
  },
  {
    nome: "Válvula 3/2 vias",
    projeto_id: "Soar",
    quantidade: 1,
    prateleira: "3",
    piso_andar: "P1",
    local_setor: "B",
    organizador: "19",
  },
  {
    nome: "Cabo de rede cinza",
    projeto_id: "Mada",
    quantidade: 2,
    prateleira: "1",
    piso_andar: "P5",
    local_setor: "A",
    organizador: "8",
  },
  {
    nome: "Guia linear",
    projeto_id: "Soar",
    quantidade: 1,
    prateleira: "3",
    piso_andar: "P3",
    local_setor: "A",
    organizador: "22",
  },
  {
    nome: "Revelador",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P2",
    local_setor: "A",
    organizador: "3",
  },
  {
    nome: "Tomada Steck",
    projeto_id: "Soar",
    quantidade: 2,
    prateleira: "3",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "18",
  },
  {
    nome: "Rolamento 6000 - 2RSH SKF",
    projeto_id: "Itens consumiveis",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "42",
  },
  {
    nome: "Analisador de gás portatil",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "2",
    piso_andar: "P5",
    local_setor: "B",
    organizador: "X",
  },
  {
    nome: "Graxa para lubrificação do Manipulador",
    projeto_id: "Mada",
    quantidade: 4,
    prateleira: "1",
    piso_andar: "P5",
    local_setor: "B",
    organizador: "7",
  },
  {
    nome: "Bateria 4/LS14500",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P4",
    local_setor: "A",
    organizador: "5",
  },
  {
    nome: "Bateria 479348-2",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P4",
    local_setor: "A",
    organizador: "5",
  },
  {
    nome: "Bateria LS14500-YA",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P4",
    local_setor: "A",
    organizador: "5",
  },
  {
    nome: "Bico de contato",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P4",
    local_setor: "A",
    organizador: "5",
  },
  {
    nome: "Bico de contato M8x1.5x30 A/1.0",
    projeto_id: "Mada",
    quantidade: 7,
    prateleira: "4",
    piso_andar: "P4",
    local_setor: "B",
    organizador: "34",
  },
  {
    nome: "Drive roll kit KP1505-0455",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P4",
    local_setor: "A",
    organizador: "5",
  },
  {
    nome: "Conduite 1,2mm aço",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "16",
  },
  {
    nome: "Disco de corte 115x1x22,23mm",
    projeto_id: "Itens consumiveis",
    quantidade: 4,
    prateleira: "10",
    piso_andar: "P2",
    local_setor: "B",
    organizador: "44",
  },
  {
    nome: "Disco de corte 115x1x22,23mm",
    projeto_id: "Itens consumiveis",
    quantidade: 2,
    prateleira: "10",
    piso_andar: "P2",
    local_setor: "B",
    organizador: "44",
  },
  {
    nome: "Monitor 27''",
    projeto_id: "",
    quantidade: 1,
    prateleira: "",
    piso_andar: "",
    local_setor: "",
    organizador: "",
  },
  {
    nome: "Caixa 19",
    projeto_id: "Soar",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P1",
    local_setor: "B",
    organizador: "19",
  },
  {
    nome: "Chave allen 14mm",
    projeto_id: "Ferramentas",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P5",
    local_setor: "A",
    organizador: "49",
  },
  {
    nome: "Fita Isolante 19mm x 20m",
    projeto_id: "VBA",
    quantidade: 1,
    prateleira: "4",
    piso_andar: "P2",
    local_setor: "B",
    organizador: "30",
  },
  {
    nome: "Chave seletora",
    projeto_id: "Itens consumiveis",
    quantidade: 1,
    prateleira: "9",
    piso_andar: "P2",
    local_setor: "B",
    organizador: "54",
  },
  {
    nome: "Sensor indutivo M12",
    projeto_id: "Itens consumiveis",
    quantidade: 9,
    prateleira: "9",
    piso_andar: "P2",
    local_setor: "A",
    organizador: "53",
  },
  {
    nome: "Broca de videa 20x210",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "1",
  },
  {
    nome: "Broca de videa 18x310",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "1",
  },
  {
    nome: "Broca de videa 16x160",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "1",
  },
  {
    nome: "Broca de videa 24X260",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "1",
  },
  {
    nome: "Monitor 24\"",
    projeto_id: "revite",
    quantidade: 1,
    prateleira: "6",
    piso_andar: "P5",
    local_setor: "AB",
    organizador: "X",
  },
  {
    nome: "Chumbador químico",
    projeto_id: "Mada",
    quantidade: 4,
    prateleira: "4",
    piso_andar: "P4",
    local_setor: "B",
    organizador: "34",
  },
  {
    nome: "Disco de corte 115x1x22,23mm",
    projeto_id: "Itens consumiveis",
    quantidade: 25,
    prateleira: "10",
    piso_andar: "P2",
    local_setor: "B",
    organizador: "44",
  },
  {
    nome: "Disco de corte 115x1x22,23",
    projeto_id: "Itens consumiveis",
    quantidade: 9,
    prateleira: "10",
    piso_andar: "P2",
    local_setor: "B",
    organizador: "44",
  },
  {
    nome: "Tinta 2L",
    projeto_id: "Soar",
    quantidade: 2,
    prateleira: "3",
    piso_andar: "P3",
    local_setor: "B",
    organizador: "23",
  },
  {
    nome: "Escova tubular nylon kit",
    projeto_id: "Soar",
    quantidade: 16,
    prateleira: "3",
    piso_andar: "P2",
    local_setor: "A",
    organizador: "20",
  },
  {
    nome: "Pirometro",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P2",
    local_setor: "MEIO",
    organizador: "X",
  },
  {
    nome: "Disco abrasivo de corte 180x1,6x22,23 BOSCH",
    projeto_id: "Itens consumiveis",
    quantidade: 16,
    prateleira: "10",
    piso_andar: "P3",
    local_setor: "A",
    organizador: "45",
  },
  {
    nome: "Cabo DVI 5 metros",
    projeto_id: "Mada",
    quantidade: 1,
    prateleira: "1",
    piso_andar: "P5",
    local_setor: "B",
    organizador: "7",
  },
  {
    nome: "Disco de desbaste 115x22,23mm",
    projeto_id: "Itens consumiveis",
    quantidade: 1,
    prateleira: "10",
    piso_andar: "P3",
    local_setor: "A",
    organizador: "45",
  },
  {
    nome: "Kit gravação eletroquímico",
    projeto_id: "revite",
    quantidade: 1,
    prateleira: "2",
    piso_andar: "P3",
    local_setor: "A",
    organizador: "13",
  },
  {
    nome: "Sensor indutivo M12",
    projeto_id: "Soar",
    quantidade: 1,
    prateleira: "3",
    piso_andar: "P1",
    local_setor: "A",
    organizador: "18",
  },
];
